[idrive_e2_rdkx5]
type = s3
provider = Other
access_key_id = Bamzf7cDKa05n5ZxZaHf
secret_access_key = zFQ8giwNnBf6uB5eAFceKJqfylx7mlMDvF2xKmd2
region = ap-southeast-1
endpoint = s3.ap-southeast-1.idrivee2.com

